name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Kotlin Linter
    # You may pin to the exact commit or the version.
    # uses: vroy/gha-kotlin-linter@cc07012076be6290c62ce565e1a8e363d2efbfed
      uses: vroy/gha-kotlin-linter@v3
      # with:
      # A list of patterns to pass along to the ktlint command
        # patterns: # optional, default is **/*.kt
